fix: Comment

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 # check if argument was provided
-if [ -z "$1" ]; then
-    echo "Error: Enter a username name"
-    exit 1
-fi
+# if [ -z "$1" ]; then
+#     echo "Error: Enter a username name"
+#     exit 1
+# fi
 
 sudo -u "$1" whoami
